on:
  release:
    types: [created]

jobs:
  go-release:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goos: [linux]
        goarch: ["amd64"]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: "arm"
            goos: darwin
          - goarch: "arm"
            goos: windows
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Release frontend
      uses: wangyoucao577/go-release-action@v1.40
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        project_path: "./frontend"
        binary_name: "bird-lg-go"

    - name: Release proxy
      uses: wangyoucao577/go-release-action@v1.40
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        project_path: "./proxy"
        binary_name: "bird-lgproxy-go"

  docker-release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build frontend docker image
        uses: docker/build-push-action@v4
        with:
          context: '{{defaultContext}}:frontend'
          platforms: linux/amd64
          push: true
          tags: |
            enbitcon/bird-lg-go:latest
            enbitcon/bird-lg-go:${{ github.event.release.tag_name }}
            ghcr.io/enbitcon/bird-lg-go:frontend
            ghcr.io/enbitcon/bird-lg-go:frontend-${{ github.event.release.tag_name }}

      - name: Build proxy docker image
        uses: docker/build-push-action@v4
        with:
          context: '{{defaultContext}}:proxy'
          platforms: linux/amd64
          push: true
          tags: |
            enbitcon/bird-lgproxy-go:latest
            enbitcon/bird-lgproxy-go:${{ github.event.release.tag_name }}
            ghcr.io/enbitcon/bird-lg-go:proxy
            ghcr.io/enbitcon/bird-lg-go:proxy-${{ github.event.release.tag_name }}
